version: 1
update_configs:
  - package_manager: "javascript"
    update_schedule: "weekly"
    directory: "/"
    default_reviewers:
      - "Hyperkid123"
    allowed_updates:
      - match:
          dependency_name: "@redhat-cloud-services/frontend*"
      - match:
          dependency_name: "react"
          dependency_type: "direct"
      - match:
          dependency_name: "react-dom"
          dependency_type: "direct"
      - match:
          dependency_name: "@patternfly/*"
          dependency_type: "direct"
